import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { Button, Card, Flex, TextInput } from "@mantine/core";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Superdocs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Chat with our existing repositories 
          </p>
          <div>
              <Link href="/chat/mantine" style={{textDecorationLine: 'underline'}}>
                Mantine
              </Link>
          </div>
        </div>

        <div className={styles.center}>
          <h1><b>Coming soon</b> Superdocs Personal</h1> <br/>
          <Flex style={{flexDirection: 'row'}}>
            <TextInput size="lg" m='md' placeholder="Your email" ></TextInput>
            <Button size="lg" m='md'>Join the waitlist</Button>
          </Flex>
        </div>

        <div className={styles.grid}>
          <Card className={styles.card} shadow="sm" padding="lg" m={'md'} radius="md" withBorder>
            OpenAI Integration
          </Card>
          <Card className={styles.card}  shadow="sm" padding="lg" m={'md'} radius="md" withBorder>
            Multiple data sources
          </Card>
          <Card className={styles.card}  shadow="sm" padding="lg" m={'md'} radius="md" withBorder>
            Search engine integration
          </Card>
          <Card className={styles.card}  shadow="sm" padding="lg" m={'md'} radius="md" withBorder>
            Faster results
          </Card>
        </div>
      </main>
    </>
  )
}
