import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Container, Input, Button } from '@chakra-ui/react';
import supabase from '../utils/supabase';
import { useRouter } from 'next/navigation';
import React, {useEffect, } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { push } = useRouter();

  useEffect(() => {
    // console.log(supabase.auth.getUser());
    supabase.auth.onAuthStateChange((event, session) => {
      if(!session?.user){
        push("/auth")
      }
    });
  }, []);


  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>

        </div>
      </main>
    </>
  )
}
