import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Container, Input, Button, Text, VStack } from '@chakra-ui/react';
import supabase from '../utils/supabase';
import { useRouter } from 'next/navigation';
import React, {useEffect, useState} from 'react';
import ChatPage from './chat/[uid]/page';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { push } = useRouter();
  const [userInfo, setUserInfo] = useState(null);

  useEffect(() => {
    // console.log(supabase.auth.getUser());
    loadInformation();
    supabase.auth.onAuthStateChange((event, session) => {
      if(!session?.user){
        push("/auth")
      }
    });
  }, []);

  let loadInformation = async() => {
    setUserInfo(await supabase.auth.getUser());
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <VStack>
            <Text>{userInfo ? userInfo["data"]["user"]["email"] : ""}</Text>
            <Button onClick={() => push("/model")}>Manage your model</Button>
            <Button onClick={() => supabase.auth.signOut()}>Sign out</Button>
          </VStack>

          <ChatPage/>
        </div>
      </main>
    </>
  )
}
